"""从 CLAUDE.md 的 <!-- ANCHOR:start/end --> 区段生成 core/orchestrator.md。
用法：gen_orchestrator.py            # 生成/覆盖 orchestrator.md
     gen_orchestrator.py --check    # 仅校验已存在副本与重生成是否一致（CI/test 用）"""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pm_paths import FRAMEWORK_ROOT

# CLAUDE.md 在仓根：plugins/pm → plugins → <REPO>
def find_claude_md():
    for cand in (
        FRAMEWORK_ROOT.parent.parent / "CLAUDE.md",  # <REPO>/CLAUDE.md
        FRAMEWORK_ROOT / "CLAUDE.md",                # git-copy 同级回退
    ):
        if cand.exists():
            return cand
    raise SystemExit("找不到 CLAUDE.md")

ANCHOR = re.compile(r"<!-- ANCHOR:start -->(.*?)<!-- ANCHOR:end -->", re.S)
HEADER = (
    "<!-- GENERATED by gen_orchestrator.py from CLAUDE.md anchors. DO NOT EDIT. -->\n"
    "<!-- 真源 = 仓根 CLAUDE.md 的 ANCHOR 区段；改这里无效，改 CLAUDE.md 后重生成。-->\n\n"
    "# 编排器常驻锚\n\n"
    "> 框架文件位于插件根（运行时由 SessionStart 注入绝对路径）；所有 `pm-workflow/...` "
    "路径相对该根解析；用户产物 `outputs/`、`process_record/` 相对项目 cwd。\n\n"
)


def build():
    src = find_claude_md().read_text(encoding="utf-8")
    blocks = [m.group(1).strip() for m in ANCHOR.finditer(src)]
    if not blocks:
        # 上游暂不瘦身：无锚 → 整份 CLAUDE.md 逐字复制（当前路径）
        blocks = [src.strip()]
    return HEADER + "\n\n---\n\n".join(blocks) + "\n"


def main():
    target = FRAMEWORK_ROOT / "pm-workflow" / "core" / "orchestrator.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    new = build()
    if "--check" in sys.argv:
        cur = target.read_text(encoding="utf-8") if target.exists() else ""
        if cur != new:
            print("orchestrator.md 过期，请运行 gen_orchestrator.py 重生成")
            sys.exit(1)
        print("orchestrator.md in sync")
        return
    target.write_text(new, encoding="utf-8")
    print(f"written {target}")


if __name__ == "__main__":
    main()
